//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pindividual.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aviones
    {
        public int Id { get; set; }
        public string Modelo { get; set; }
        public string Asientos { get; set; }
        public int Cantidad { get; set; }
    }
}
